Layout/IndentHeredoc:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

# Hell no
Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false

