AllCops:
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'
    - '**/*_spec.rb'

Layout/IndentHeredoc:
  Enabled: false

# Blank lines are fine
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

# Hell no
Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# trailing commas improve diff clarity at no cost to readability
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false

